[package]
name = "syndica"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.3"
tokio = "1.44.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
